namespace SportifyApi.DTOs
{
    public class AchievementDto
    {
        public int AchievementId { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public bool IsAutoGenerated { get; set; }
    }
}
