namespace SportifyApi.Dtos
{
    public class AchievementDto
    {
        public int AchievementId { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string IconUrl { get; set; } = string.Empty;
        public string SportType { get; set; } = string.Empty;
        public bool IsAutoGenerated { get; set; } = false;
        public DateTime? DateAwarded { get; set; }
    }
}