using SportifyApi.Models;

namespace SportifyApi.Data
{
    public static class DbSeeder
    {
        public static void SeedAchievements(AppDbContext context)
        {
            var predefined = new List<Achievement>
            {
                // 🏉 Rugby
                new() { Title = "🏉 Man of the Match", Description = "Top-performing player", SportType = "Rugby", IconUrl = "https://cdn-icons-png.flaticon.com/512/1055/1055672.png", IsAutoGenerated = false },
                new() { Title = "💪 Best Tackler", Description = "Most effective in defense", SportType = "Rugby", IconUrl = "https://cdn-icons-png.flaticon.com/512/2848/2848919.png", IsAutoGenerated = false },

                // ⚽ Soccer
                new() { Title = "⚽ Top Scorer", Description = "Most goals scored", SportType = "Soccer", IconUrl = "https://cdn-icons-png.flaticon.com/512/883/883407.png", IsAutoGenerated = false },
                new() { Title = "🧤 Best Goalkeeper", Description = "Outstanding defensive performance", SportType = "Soccer", IconUrl = "https://cdn-icons-png.flaticon.com/512/2886/2886696.png", IsAutoGenerated = false },
                new() { Title = "🏆 MVP", Description = "Most valuable player", SportType = "Soccer", IconUrl = "https://cdn-icons-png.flaticon.com/512/1055/1055646.png", IsAutoGenerated = false },

                // 🏃 Running
                new() { Title = "🥇 First Place", Description = "Winner of the race", SportType = "Running", IconUrl = "https://cdn-icons-png.flaticon.com/512/3514/3514491.png", IsAutoGenerated = false },
                new() { Title = "🥈 Second Place", Description = "Runner-up", SportType = "Running", IconUrl = "https://cdn-icons-png.flaticon.com/512/2583/2583427.png", IsAutoGenerated = false },
                new() { Title = "🥉 Third Place", Description = "Third-place finisher", SportType = "Running", IconUrl = "https://cdn-icons-png.flaticon.com/512/2583/2583428.png", IsAutoGenerated = false },

                // 🏊 Swimming
                new() { Title = "🏊 Best Swimmer", Description = "Fastest swimmer", SportType = "Swimming", IconUrl = "https://cdn-icons-png.flaticon.com/512/3208/3208744.png", IsAutoGenerated = false },

                // 🏀 Basketball
                new() { Title = "🏀 MVP", Description = "Top player of the match", SportType = "Basketball", IconUrl = "https://cdn-icons-png.flaticon.com/512/2891/2891137.png", IsAutoGenerated = false },
                new() { Title = "🎯 Most 3-Pointers", Description = "Most successful 3-point shots", SportType = "Basketball", IconUrl = "https://cdn-icons-png.flaticon.com/512/3138/3138533.png", IsAutoGenerated = false },

                // 🏈 Football
                new() { Title = "🏈 MVP", Description = "Most valuable player", SportType = "Football", IconUrl = "https://cdn-icons-png.flaticon.com/512/3364/3364823.png", IsAutoGenerated = false },
                new() { Title = "🚀 Longest Throw", Description = "Best passing distance", SportType = "Football", IconUrl = "https://cdn-icons-png.flaticon.com/512/1296/1296551.png", IsAutoGenerated = false },

                // 🏏 Cricket
                new() { Title = "🏏 Best Batsman", Description = "Top run scorer", SportType = "Cricket", IconUrl = "https://cdn-icons-png.flaticon.com/512/2937/2937996.png", IsAutoGenerated = false },
                new() { Title = "🔥 Best Bowler", Description = "Most wickets taken", SportType = "Cricket", IconUrl = "https://cdn-icons-png.flaticon.com/512/2937/2937933.png", IsAutoGenerated = false },

                // 🎾 Tennis
                new() { Title = "🎾 Ace Leader", Description = "Most aces served", SportType = "Tennis", IconUrl = "https://cdn-icons-png.flaticon.com/512/1736/1736343.png", IsAutoGenerated = false },
                new() { Title = "🏆 Tournament Winner", Description = "Overall tennis champion", SportType = "Tennis", IconUrl = "https://cdn-icons-png.flaticon.com/512/1055/1055651.png", IsAutoGenerated = false },

                // 🏓 Table Tennis
                new() { Title = "🏓 Champion", Description = "Tournament winner", SportType = "Table Tennis", IconUrl = "https://cdn-icons-png.flaticon.com/512/3964/3964806.png", IsAutoGenerated = false },

                // 🥋 Judo / Karate
                new() { Title = "🥋 Best Technique", Description = "Cleanest moves", SportType = "Judo", IconUrl = "https://cdn-icons-png.flaticon.com/512/2172/2172383.png", IsAutoGenerated = false },

                // 🚴 Cycling
                new() { Title = "🚴 King of the Mountain", Description = "Best climber", SportType = "Cycling", IconUrl = "https://cdn-icons-png.flaticon.com/512/235/235861.png", IsAutoGenerated = false },

                // 🏇 Horse Racing
                new() { Title = "🏇 Fastest Finish", Description = "Top performer", SportType = "Horse Racing", IconUrl = "https://cdn-icons-png.flaticon.com/512/1287/1287710.png", IsAutoGenerated = false },

                // 🥊 Boxing
                new() { Title = "🥊 Knockout King", Description = "Best boxer", SportType = "Boxing", IconUrl = "https://cdn-icons-png.flaticon.com/512/1394/1394386.png", IsAutoGenerated = false },

                // 🧗 Climbing
                new() { Title = "🧗 Highest Climb", Description = "Most difficult climb", SportType = "Climbing", IconUrl = "https://cdn-icons-png.flaticon.com/512/4035/4035586.png", IsAutoGenerated = false },
            };

            // ✅ Auto achievements (e.g. First join, 100 joins)
            predefined.AddRange(new[]
            {
                new Achievement
                {
                    Title = "First Event Joined",
                    Description = "Awarded for joining your first event",
                    SportType = "General",
                    IconUrl = "https://cdn-icons-png.flaticon.com/512/1041/1041916.png",
                    IsAutoGenerated = true
                },
                new Achievement
                {
                    Title = "100 Events Joined",
                    Description = "You've joined 100 events!",
                    SportType = "General",
                    IconUrl = "https://cdn-icons-png.flaticon.com/512/1422/1422519.png",
                    IsAutoGenerated = true
                },
                new Achievement
                {
                    Title = "Joined 5 Events",
                    Description = "You're starting to get active!",
                    SportType = "General",
                    IconUrl = "https://cdn-icons-png.flaticon.com/512/4380/4380890.png",
                    IsAutoGenerated = true
                }
            });

            foreach (var achievement in predefined)
            {
                if (!context.Achievements.Any(a => a.Title == achievement.Title && a.SportType == achievement.SportType))
                {
                    context.Achievements.Add(achievement);
                }
            }

            context.SaveChanges();
        }
    }
}
