using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace SportifyApi.Models
{
    public class Achievement
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AchievementId { get; set; }

        [Required]
        public string Title { get; set; } = string.Empty;

        [Required]
        public string Description { get; set; } = string.Empty;

        [Required]
        public string SportType { get; set; } = string.Empty;

        public string IconUrl { get; set; } = string.Empty;

        public bool IsAutoGenerated { get; set; } = false;

        [JsonIgnore] 
        public ICollection<UserAchievement> UserAchievements { get; set; } = new List<UserAchievement>();
    }
}

