name: Sportify CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

- name: Restore dependencies
  run: dotnet restore SportifyApi.sln

- name: Build the backend
  run: dotnet build SportifyApi.sln --no-restore --configuration Release

- name: Run unit tests
  run: dotnet test SportifyApi.sln --no-build --configuration Release


